package com.example.wallrush.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    ARABIC("ar", "Arabic", "العربية")
}

object Strings {
    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.ARABIC) ARABIC_MAP else ENGLISH_MAP
        return dict[key] ?: ENGLISH_MAP[key] ?: key
    }

    private val ENGLISH_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "Block their way, clear yours",
        "quick_match" to "Quick Match",
        "quick_match_sub" to "Find a live opponent",
        "play_online" to "Play Online",
        "play_online_sub" to "Live Public Rooms",
        "play_friend" to "Play a Friend",
        "play_friend_sub" to "Hotspot / Wi-Fi & Bluetooth",
        "play_ai" to "Play Against AI",
        "play_ai_sub" to "Strategic Practice Mode",
        "pass_and_play" to "Pass & Play",
        "pass_and_play_sub" to "2 Players on 1 Device",
        "race_mode" to "Race Mode",
        "race_mode_sub" to "Sprint to the finish line from the same side!",
        "quad_mode" to "Quad Mode (4 Players)",
        "quad_mode_sub" to "4 sides, 4 players, 1 center goal!",
        "quad_center_goal" to "First to the center square wins!",
        "race_finish_line" to "Finish Line",
        "race_start_line" to "Starting Line",
        "steps_to_finish" to "steps to finish",
        "winner_player3" to "Player 3 Wins!",
        "winner_player4" to "Player 4 Wins!",
        "quad_pass_and_play" to "Local Quad (4 Players)",
        "quad_vs_ai" to "Quad vs 3 Bots",
        "how_to_play" to "How to Play",
        "how_to_play_sub" to "Rules & Interactive Tutorial",
        "leaderboard" to "Leaderboard",
        "profile" to "Profile",
        "settings" to "Settings",
        "match_history" to "Match History",
        "replays" to "Replays",
        "searching_opponent" to "Searching for live opponent...",
        "cancel" to "Cancel",
        "ready" to "Ready",
        "countdown" to "Match Starts In",
        "your_turn" to "YOUR TURN",
        "opponents_turn" to "OPPONENT'S TURN",
        "walls_remaining" to "Walls Remaining",
        "place_wall" to "Place Wall",
        "cancel_wall" to "Cancel",
        "rotate_wall" to "Rotate (H/V)",
        "confirm_wall" to "Confirm Placement",
        "horizontal" to "Horizontal",
        "vertical" to "Vertical",
        "resign" to "Resign",
        "resign_confirm_title" to "Surrender Match?",
        "resign_confirm_desc" to "Are you sure you want to forfeit this match?",
        "rematch" to "Rematch",
        "menu" to "Main Menu",
        "you_win" to "VICTORY!",
        "you_lose" to "DEFEAT",
        "draw" to "DRAW",
        "winner_player1" to "Player 1 Wins!",
        "winner_player2" to "Player 2 Wins!",
        "goal_reached" to "Reached the opponent's baseline!",
        "time_out" to "Won on time expiration!",
        "resigned_reason" to "Opponent conceded victory!",
        "disconnected_reason" to "Opponent disconnected! Match terminated.",
        "create_room" to "Create Room",
        "join_room" to "Join Room",
        "enter_room_code" to "Enter Host IP or Room Code",
        "room_code" to "Room Code",
        "copy_code" to "Copy Code",
        "share_code" to "Share Code",
        "waiting_for_player" to "Waiting for opponent to join...",
        "room_full" to "Room is full",
        "room_not_found" to "Room not found",
        "public_rooms" to "Public Live Rooms",
        "no_rooms_available" to "No public rooms available. Create one!",
        "refresh" to "Refresh",
        "difficulty" to "AI Difficulty",
        "easy" to "Easy",
        "medium" to "Medium",
        "hard" to "Expert",
        "time_control" to "Time Control",
        "infinite" to "Unlimited",
        "3_min" to "3 Minutes",
        "5_min" to "5 Minutes",
        "walls_count" to "Wall Count",
        "10_walls" to "10 Walls",
        "15_walls" to "15 Walls",
        "sound_effects" to "Sound Effects",
        "vibration" to "Haptic Feedback",
        "confirm_wall_toggle" to "Require Placement Confirmation",
        "show_legal_moves" to "Show Legal Move Indicators",
        "language" to "Language",
        "game_theme" to "Game Theme",
        "theme_cyber_neon" to "Cyber Neon (Main)",
        "theme_cyber_neon_desc" to "Glowing neon grid with electric cyan & magenta neon walls",
        "theme_deep_slate" to "Deep Slate (Classic)",
        "theme_deep_slate_desc" to "Calm dark slate canvas with modern blue & crimson accents",
        "theme_royal_emerald" to "Royal Emerald",
        "theme_royal_emerald_desc" to "Luxurious deep emerald board with royal brass gold walls",
        "theme_classic_wood" to "Classic Mahogany Wood",
        "theme_classic_wood_desc" to "Rich mahogany wooden finish with antique brass accents",
        "theme_obsidian_amber" to "Obsidian Amber",
        "theme_obsidian_amber_desc" to "Sleek charcoal obsidian with radiant amber gold tones",
        "username" to "Player Name",
        "save" to "Save",
        "settings_saved" to "Settings saved successfully",
        "total_games" to "Total Matches",
        "wins" to "Victories",
        "losses" to "Defeats",
        "win_rate" to "Win Rate",
        "streak" to "Winning Streak",
        "best_streak" to "Best Streak",
        "rating" to "Elo Rating",
        "total_walls" to "Walls Placed",
        "replay_title" to "Match Replay",
        "move_number" to "Move",
        "step_first" to "Start",
        "step_prev" to "Back",
        "step_play" to "Play",
        "step_pause" to "Pause",
        "step_next" to "Next",
        "step_last" to "End",
        "tutorial_title" to "Interactive Tutorial",
        "tut_step_1_title" to "1. Basic Movement",
        "tut_step_1_desc" to "Tap your pawn and step into any adjacent unblocked square. Your goal is to reach any square in the opponent's starting row!",
        "tut_step_2_title" to "2. Wall Placement",
        "tut_step_2_desc" to "Walls span 2 squares. Place them horizontally or vertically to lengthen your opponent's path.",
        "tut_step_3_title" to "3. Jumping Rivals",
        "tut_step_3_desc" to "When adjacent to an opponent, leap directly over them! If a wall is behind them, you can jump diagonally.",
        "tut_step_4_title" to "4. The Golden Rule: No Trapping",
        "tut_step_4_desc" to "You may never completely seal off a player from their goal. At least one open route must always exist!",
        "tut_step_5_title" to "5. Victory Condition",
        "tut_step_5_desc" to "The first player whose pawn touches any square in the opponent's starting row wins immediately!",

        // Real Network & P2P Keys
        "no_internet_title" to "No Internet Connection",
        "no_internet_msg" to "Online play requires an active internet connection. Please enable Wi-Fi or Mobile Data to play online.",
        "ok" to "OK",
        "p2p_mode_title" to "Play with a Nearby Friend",
        "p2p_mode_desc" to "Connect directly via Hotspot, Wi-Fi, or Bluetooth without needing external servers!",
        "p2p_method_wifi" to "Hotspot / Local Wi-Fi",
        "p2p_method_bt" to "Bluetooth P2P",
        "p2p_host_title" to "Host a Match (Player 1)",
        "p2p_join_title" to "Join Match as Guest (Player 2)",
        "p2p_host_btn" to "Start Hosting Server",
        "p2p_join_btn" to "Connect to Friend",
        "p2p_my_ip" to "Your Local IP Address:",
        "p2p_enter_ip" to "Enter Host IP Address:",
        "p2p_connecting" to "Connecting to friend...",
        "p2p_connected" to "Connected successfully!",
        "p2p_listening" to "Waiting for friend to connect on this network...",
        "p2p_disconnected_title" to "Friend Disconnected",
        "p2p_disconnected_msg" to "Connection with your friend was lost! The match has been terminated.",
        "p2p_bt_paired" to "Paired Devices (Phones & Tablets)",
        "p2p_bt_no_devices" to "No paired Bluetooth devices found. Please pair devices in Android settings first.",
        "p2p_bt_no_phones" to "No paired phones or tablets found. Non-gaming devices (headsets, watches, speakers) are automatically hidden.",
        "p2p_bt_phones_only" to "Phones & Tablets Only",
        "p2p_bt_all_devices" to "Show All Devices",
        "p2p_bt_host_listening" to "Bluetooth host active. Waiting for connection...",
        "p2p_bt_disabled" to "Bluetooth is currently turned off. Please turn it on in device settings.",
        "about" to "About WallRush",
        "developer_label" to "Programmed & Developed by:",
        "developer_name" to "Majd Anwar",
        "contact_label" to "Contact:",
        "contact_phone" to "+967 735 465 673",
        "email_label" to "Email:",
        "email_address" to "majd7772233@gmail.com",
        "phone_copied_dialer" to "Phone number copied & dialer opened",
        "email_copied" to "Email copied to clipboard",
        "app_full_desc" to "WallRush is an epic strategic mind game inspired by the legendary Quoridor. Outsmart your opponents, build walls to hinder their progress, and carve your path to victory!",
        "audio_haptics" to "Audio & Haptics",
        "gameplay_rules" to "Gameplay & Board",
        "reset_stats" to "Reset Statistics",
        "reset_stats_confirm" to "Are you sure you want to reset all match statistics? This action cannot be undone.",
        "waiting_room_title" to "Room Created - Waiting for Player",
        "waiting_room_desc" to "Your room is open. Waiting for someone to join...",
        "player_challenge_title" to "Player wants to play with you!",
        "accept" to "Accept",
        "reject" to "Reject",
        "searching_live_players" to "Searching for live players...",
        "matching_opponent" to "Matching with opponent...",
        "opponent_found" to "Opponent found! Initializing board...",
        "local_p1_victory_title" to "YOU WON THE MATCH!",
        "local_p2_victory_title" to "YOU WON THE MATCH!",
        "local_p1_loss_title" to "DEFEAT",
        "local_p2_loss_title" to "DEFEAT",
        "back_to_menu" to "Back to Main Menu",
        "race_mode" to "Race Mode 🏁",
        "race_mode_sub" to "Start on the same side and race to the finish line!",
        "quad_mode" to "Quad Mode (4 Players) 🎯",
        "quad_mode_sub" to "4 players entering from 4 sides racing to the board center!",
        "quad_center_goal" to "First to reach the center square wins!",
        "race_finish_line" to "Finish Line 🏁",
        "race_start_line" to "Starting Line 🚦",
        "steps_to_finish" to "steps to finish",
        "winner_player3" to "Player 3 (Green) Wins!",
        "winner_player4" to "Player 4 (Yellow) Wins!",
        "quad_pass_and_play" to "Quad Local (4 Players)",
        "quad_vs_ai" to "Quad vs 3 AI Bots",
        "race_vs_ai" to "Race vs AI",
        "race_pass_and_play" to "Race Local 2 Players",
        "classic_mode" to "Classic Match ⚔️",
        "classic_mode_sub" to "Reach the opposite edge of the board first!",
        "classic_mode_short" to "Classic ⚔️",
        "race_mode_short" to "Race 🏁",
        "quad_mode_short" to "Quad 4P 🎯",
        "select_game_mode" to "Select Game Mode",
        "ai_settings_title" to "Play vs AI Setup",
        "ai_setup_title" to "Play vs AI Setup",
        "select_difficulty" to "Difficulty Level",
        "walls_count" to "Walls Count",
        "time_control" to "Time Limit",
        "bt_supports_2p_only" to "Bluetooth connection supports 2 paired players (Classic & Race modes only)",
        "start_match" to "Start Match",
        "start_game" to "Start Game"
    )

    private val ARABIC_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "اقطع طريق الخصم، وافتح طريقك",
        "quick_match" to "مباراة سريعة",
        "quick_match_sub" to "بحث فوري عن خصم حقيقي",
        "play_online" to "اللعب أونلاين",
        "play_online_sub" to "غرف عامة حية ومتجددة",
        "play_friend" to "العب مع صديق",
        "play_friend_sub" to "نقطة اتصال / واي فاي أو بلوتوث",
        "play_ai" to "اللعب ضد الذكاء الاصطناعي",
        "play_ai_sub" to "وضع التدريب التكتيكي",
        "pass_and_play" to "لعب محلي لشخصين",
        "pass_and_play_sub" to "لاعبان على نفس الشاشة",
        "race_mode" to "وضع السباق 🏁",
        "race_mode_sub" to "انطلاق من نفس الجهة والسباق نحو خط النهاية!",
        "quad_mode" to "الوضع الرباعي (٤ لاعبين) 🎯",
        "quad_mode_sub" to "٤ لاعبين من ٤ جهات يتسابقون نحو مربع المنتصف!",
        "quad_center_goal" to "أول من يصل إلى مربع المنتصف يفوز!",
        "race_finish_line" to "خط النهاية 🏁",
        "race_start_line" to "خط البداية 🚦",
        "steps_to_finish" to "خطوات للنهاية",
        "winner_player3" to "فاز اللاعب الثالث (الأخضر)!",
        "winner_player4" to "فاز اللاعب الرابع (الأصفر)!",
        "quad_pass_and_play" to "رباعي محلي (٤ لاعبين)",
        "quad_vs_ai" to "رباعي ضد ٣ روبوتات",
        "race_vs_ai" to "سباق ضد الذكاء الاصطناعي",
        "race_pass_and_play" to "سباق محلي لشخصين",
        "classic_mode" to "المباراة الكلاسيكية ⚔️",
        "classic_mode_sub" to "الوصول إلى الصف المقابل للخصم أولاً!",
        "classic_mode_short" to "كلاسيكي ⚔️",
        "race_mode_short" to "سباق 🏁",
        "quad_mode_short" to "رباعي ٤ لاعبين 🎯",
        "select_game_mode" to "اختر وضع اللعبة",
        "ai_settings_title" to "إعدادات اللعب ضد الذكاء الاصطناعي",
        "ai_setup_title" to "إعدادات اللعب ضد الذكاء الاصطناعي",
        "select_difficulty" to "مستوى الصعوبة",
        "walls_count" to "عدد الجدران",
        "time_control" to "الوقت المحدد",
        "bt_supports_2p_only" to "اتصال البلوتوث يدعم جهازين مقترنين فقط (الوضع الكلاسيكي ووضع السباق)",
        "start_match" to "ابدأ المباراة",
        "start_game" to "ابدأ اللعبة",
        "how_to_play" to "كيفية اللعب",
        "how_to_play_sub" to "القواعد والتدريب التفاعلي",
        "leaderboard" to "لوحة الصدارة",
        "profile" to "الملف الشخصي",
        "settings" to "الإعدادات",
        "match_history" to "سجل المباريات",
        "replays" to "إعادة المباريات",
        "searching_opponent" to "جارٍ البحث عن خصم متصل...",
        "cancel" to "إلغاء",
        "ready" to "جاهز",
        "countdown" to "تبدأ المباراة خلال",
        "your_turn" to "دورك الآن",
        "opponents_turn" to "دور الخصم الآن",
        "walls_remaining" to "الجدران المتبقية",
        "place_wall" to "وضع جدار",
        "cancel_wall" to "إلغاء",
        "rotate_wall" to "تدوير (أفقي / رأسي)",
        "confirm_wall" to "تثبيت الجدار",
        "horizontal" to "أفقي",
        "vertical" to "رأسي",
        "resign" to "استسلام",
        "resign_confirm_title" to "هل ترغب في الاستسلام؟",
        "resign_confirm_desc" to "هل أنت متأكد من رغبتك في إعلان الانسحاب وخسارة الجولة؟",
        "rematch" to "إعادة اللعب",
        "menu" to "القائمة الرئيسية",
        "you_win" to "انتصار ساحق!",
        "you_lose" to "هزيمة",
        "draw" to "تعادل",
        "winner_player1" to "فاز اللاعب الأول!",
        "winner_player2" to "فاز اللاعب الثاني!",
        "goal_reached" to "وصل بقطعته إلى خط نهاية الخصم!",
        "time_out" to "فوز بانتهاء وقت الخصم!",
        "resigned_reason" to "استسلم الخصم وأعلن انسحابه!",
        "disconnected_reason" to "انقطع اتصال الخصم! انتهت المباراة.",
        "create_room" to "إنشاء غرفة",
        "join_room" to "انضمام لغرفة",
        "enter_room_code" to "أدخل عنوان IP للمضيف أو الرمز",
        "room_code" to "رمز الغرفة",
        "copy_code" to "نسخ الرمز",
        "share_code" to "مشاركة الرمز",
        "waiting_for_player" to "بانتظار انضمام الخصم...",
        "room_full" to "الغرفة ممتلئة بالكامل",
        "room_not_found" to "تعذر العثور على الغرفة",
        "public_rooms" to "الغرف العامة المباشرة",
        "no_rooms_available" to "لا توجد غرف متاحة حالياً. أنشئ غرفة الآن!",
        "refresh" to "تحديث الغرف",
        "difficulty" to "مستوى الذكاء الاصطناعي",
        "easy" to "مبتدئ (سهل)",
        "medium" to "متوسط",
        "hard" to "محترف (صعب)",
        "time_control" to "نظام الوقت",
        "infinite" to "غير محدود",
        "3_min" to "3 دقائق",
        "5_min" to "5 دقائق",
        "walls_count" to "عدد الجدران لكل لاعب",
        "10_walls" to "10 جدران",
        "15_walls" to "15 جداراً",
        "sound_effects" to "المؤثرات الصوتية",
        "vibration" to "الاهتزاز اللمسي",
        "confirm_wall_toggle" to "طلب تأكيد قبل تثبيت الجدار",
        "show_legal_moves" to "إظهار مؤشرات النقلات المتاحة",
        "language" to "اللغة",
        "game_theme" to "ثيم اللعبة",
        "theme_cyber_neon" to "نيون سايبورغ (الرئيسي)",
        "theme_cyber_neon_desc" to "مظهر نيون متوهج بخطوط شبكية إلكترونية وجدران فسفورية مشعة",
        "theme_deep_slate" to "ديب سليت (الكلاسيكي المحسن)",
        "theme_deep_slate_desc" to "مظهر رمادي داكن هادئ ومريح للعين مع إضاءة زرقاء وحمراء",
        "theme_royal_emerald" to "الزمرد الملكي",
        "theme_royal_emerald_desc" to "مظهر فاخر بدرجات الزمرد الأخضر مع جدران ذهبية براقة",
        "theme_classic_wood" to "الخشب الكلاسيكي",
        "theme_classic_wood_desc" to "مظهر خشبي عريق من خشب الماهوجني الداكن ولمسات نحاسية",
        "theme_obsidian_amber" to "الأوبسيديان والكهرمان",
        "theme_obsidian_amber_desc" to "مظهر صخري داكن فخم بتفاصيل الكهرمان الدافئ والبنفسجي",
        "username" to "اسم اللاعب",
        "save" to "حفظ التغييرات",
        "settings_saved" to "تم حفظ الإعدادات بنجاح",
        "total_games" to "المباريات الملعوبة",
        "wins" to "الانتصارات",
        "losses" to "الهزائم",
        "win_rate" to "نسبة الفوز",
        "streak" to "سلسلة الانتصارات الحالية",
        "best_streak" to "أفضل سلسلة انتصارات",
        "rating" to "نقاط التصنيف (Rating)",
        "total_walls" to "الجدران المشيدة",
        "replay_title" to "إعادة عرض المباراة",
        "move_number" to "النقلة",
        "step_first" to "البداية",
        "step_prev" to "السابقة",
        "step_play" to "تشغيل",
        "step_pause" to "إيقاف مؤقت",
        "step_next" to "التالية",
        "step_last" to "النهاية",
        "tutorial_title" to "التدريب التفاعلي",
        "tut_step_1_title" to "1. الحركة الأساسية",
        "tut_step_1_desc" to "انقر على قطعتك ثم تحرك إلى أي خانة مجاورة غير محجوبة بحاجز. هدفك الأسمى هو الوصول إلى أي خانة في صف بداية الخصم المقابل!",
        "tut_step_2_title" to "2. وضع الجدران العازلة",
        "tut_step_2_desc" to "طول كل جدار خانتان كاملتان. ضعه أفقياً أو رأسياً لإطالة مسار الخصم وإجباره على الالتفاف وتضييع نقلاته.",
        "tut_step_3_title" to "3. القفز فوق المنافس",
        "tut_step_3_desc" to "عندما تتواجه قطعتك مع الخصم وجهاً لوجه، يمكنك القفز مباشرة فوقه! وإذا كان خلفه جدار عازل، يسمح لك بالقفز قطرياً.",
        "tut_step_4_title" to "4. القاعدة الذهبية: حظر الحصار الكامل",
        "tut_step_4_desc" to "يُحظر تماماً وضع جدار يغلق جميع المسارات المؤدية لخط النهاية أمام أي لاعب. يجب أن يظل هناك مسار سالك واحد على الأقل دائماً!",
        "tut_step_5_title" to "5. شروط الفوز",
        "tut_step_5_desc" to "أول لاعب تلمس قطعته أي خانة في خط بداية الخصم يفوز فوراً بالمباراة ويتوج بطلاً!",

        // Real Network & P2P Keys (اللعب ضد صديق بالبلوتوث ونقطة الاتصال والإنترنت)
        "no_internet_title" to "لا يتوفر اتصال بالإنترنت",
        "no_internet_msg" to "يتطلب وضع اللعب عبر الإنترنت اتصالاً نشطاً بالشبكة. يرجى تفعيل Wi-Fi أو بيانات الهاتف للبحث عن لاعبين والانضمام للغرف العامة.",
        "ok" to "حسناً",
        "p2p_mode_title" to "اللعب المباشر مع صديق",
        "p2p_mode_desc" to "اتصال حقيقي مباشر بين جهازين باستخدام نقطة الاتصال (Hotspot)، أو شبكة Wi-Fi محلية، أو البلوتوث الفعلي بدون الحاجة لإنترنت!",
        "p2p_method_wifi" to "نقطة اتصال (Hotspot) / Wi-Fi",
        "p2p_method_bt" to "بلوتوث (Bluetooth P2P)",
        "p2p_host_title" to "إنشاء استضافة (اللاعب 1)",
        "p2p_join_title" to "انضمام إلى الصديق (اللاعب 2)",
        "p2p_host_btn" to "بدء استضافة الغرفة",
        "p2p_join_btn" to "اتصال بجهاز الصديق",
        "p2p_my_ip" to "عنوان IP لجهازك:",
        "p2p_enter_ip" to "أدخل عنوان IP للمضيف:",
        "p2p_connecting" to "جارٍ الاتصال بجهاز الصديق...",
        "p2p_connected" to "تم الاتصال بنجاح! تبدأ المباراة الآن...",
        "p2p_listening" to "في انتظار انضمام الصديق عبر الشبكة...",
        "p2p_disconnected_title" to "انقطع الاتصال بالصديق!",
        "p2p_disconnected_msg" to "تم فقدان الاتصال بين الجهازين! توقفت اللعبة فوراً بسبب إيقاف الاتصال أو انقطاع الشبكة/البلوتوث.",
        "p2p_bt_paired" to "الأجهزة المتوافقة (الهواتف والأجهزة اللوحية)",
        "p2p_bt_no_devices" to "لا توجد أجهزة بلوتوث مقترنة. يرجى إقران الجهازين أولاً من إعدادات البلوتوث في الهاتف.",
        "p2p_bt_no_phones" to "لم يتم العثور على هواتف مقترنة. تم إخفاء السماعات والساعات والأجهزة غير المتوافقة تلقائياً.",
        "p2p_bt_phones_only" to "الهواتف فقط (مفلترة)",
        "p2p_bt_all_devices" to "عرض كل الأجهزة",
        "p2p_bt_host_listening" to "خادم البلوتوث قيد الانتظار... اطلب من صديقك الاتصال بجهازك الآن.",
        "p2p_bt_disabled" to "البلوتوث غير مفعّل حالياً على جهازك. يرجى تشغيله للمتابعة.",
        "about" to "عن التطبيق والمعلومات",
        "developer_label" to "برمجة وتطوير:",
        "developer_name" to "مجد أنور",
        "contact_label" to "للتواصل:",
        "contact_phone" to "+967 735 465 673",
        "email_label" to "البريد الإلكتروني:",
        "email_address" to "majd7772233@gmail.com",
        "phone_copied_dialer" to "تم فتح لوحة الاتصال ونسخ الرقم",
        "email_copied" to "تم نسخ البريد الإلكتروني إلى الحافظة",
        "app_full_desc" to "لعبة WallRush هي معركة ذهنية وتكتيكية ملحمية مستوحاة من لعبة كوريدور العالمية الشهيرة. اخدع خصومك، ابنِ الجدران العازلة لقطع مسارهم، وشق طريقك نحو النصر!",
        "audio_haptics" to "الصوتيات والاهتزاز",
        "gameplay_rules" to "أسلوب اللعب واللوحة",
        "reset_stats" to "إعادة تعيين الإحصائيات",
        "reset_stats_confirm" to "هل أنت متأكد من رغبتك في تصفير جميع الإحصائيات؟ لا يمكن التراجع عن هذا الإجراء.",
        "waiting_room_title" to "تم إنشاء الغرفة - بانتظار لاعب",
        "waiting_room_desc" to "غرفتك مفتوحة الآن وفي انتظار انضمام أي منافس...",
        "player_challenge_title" to "هناك لاعب يريد أن يلعب معك!",
        "accept" to "قبول",
        "reject" to "رفض",
        "searching_live_players" to "جارٍ البحث عن لاعبين نشطين...",
        "matching_opponent" to "جارٍ مطابقة المنافس...",
        "opponent_found" to "تم العثور على خصم! تهيئة رقعة اللعب...",
        "local_p1_victory_title" to "ألف مبروك! لقد فزت بالمباراة! 🏆",
        "local_p2_victory_title" to "ألف مبروك! لقد فزت بالمباراة! 🏆",
        "local_p1_loss_title" to "حظاً أوفر في المرة القادمة! (هزيمة)",
        "local_p2_loss_title" to "حظاً أوفر في المرة القادمة! (هزيمة)",
        "back_to_menu" to "العودة للشاشة الرئيسية"
    )
}
