package com.example.wallrush.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    ARABIC("ar", "Arabic", "العربية")
}

object Strings {
    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.ARABIC) ARABIC_MAP else ENGLISH_MAP
        return dict[key] ?: ENGLISH_MAP[key] ?: key
    }

    private val ENGLISH_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "Block their way, clear yours",
        "quick_match" to "Quick Match",
        "quick_match_sub" to "Find a live opponent",
        "play_online" to "Play Online",
        "play_online_sub" to "Live Public Rooms",
        "play_friend" to "Play a Friend",
        "play_friend_sub" to "Hotspot / Wi-Fi & Bluetooth",
        "play_ai" to "Play Against AI",
        "play_ai_sub" to "Strategic Practice Mode",
        "pass_and_play" to "Pass & Play",
        "pass_and_play_sub" to "2 Players on 1 Device",
        "race_mode" to "Race Mode",
        "race_mode_sub" to "Sprint to the finish line from the same side!",
        "quad_mode" to "Quad Mode (4 Players)",
        "quad_mode_sub" to "4 sides, 4 players, 1 center goal!",
        "quad_center_goal" to "First to the center square wins!",
        "race_finish_line" to "Finish Line",
        "race_start_line" to "Starting Line",
        "steps_to_finish" to "steps to finish",
        "winner_player3" to "Player 3 Wins!",
        "winner_player4" to "Player 4 Wins!",
        "quad_pass_and_play" to "Local Quad (4 Players)",
        "quad_vs_ai" to "Quad vs 3 Bots",
        "how_to_play" to "How to Play",
        "how_to_play_sub" to "Rules & Interactive Tutorial",
        "leaderboard" to "Leaderboard",
        "profile" to "Profile",
        "settings" to "Settings",
        "match_history" to "Match History",
        "replays" to "Replays",
        "searching_opponent" to "Searching for live opponent...",
        "cancel" to "Cancel",
        "ready" to "Ready",
        "countdown" to "Match Starts In",
        "your_turn" to "YOUR TURN",
        "opponents_turn" to "OPPONENT'S TURN",
        "walls_remaining" to "Walls Remaining",
        "place_wall" to "Place Wall",
        "cancel_wall" to "Cancel",
        "rotate_wall" to "Rotate (H/V)",
        "confirm_wall" to "Confirm Placement",
        "horizontal" to "Horizontal",
        "vertical" to "Vertical",
        "resign" to "Resign",
        "resign_confirm_title" to "Surrender Match?",
        "resign_confirm_desc" to "Are you sure you want to forfeit this match?",
        "rematch" to "Rematch",
        "menu" to "Main Menu",
        "you_win" to "VICTORY!",
        "you_lose" to "DEFEAT",
        "draw" to "DRAW",
        "winner_player1" to "Player 1 Wins!",
        "winner_player2" to "Player 2 Wins!",
        "goal_reached" to "Reached the opponent's baseline!",
        "time_out" to "Won on time expiration!",
        "resigned_reason" to "Opponent conceded victory!",
        "disconnected_reason" to "Opponent disconnected! Match terminated.",
        "create_room" to "Create Room",
        "join_room" to "Join Room",
        "enter_room_code" to "Enter Host IP or Room Code",
        "room_code" to "Room Code",
        "copy_code" to "Copy Code",
        "share_code" to "Share Code",
        "waiting_for_player" to "Waiting for opponent to join...",
        "room_full" to "Room is full",
        "room_not_found" to "Room not found",
        "public_rooms" to "Public Live Rooms",
        "no_rooms_available" to "No public rooms available. Create one!",
        "refresh" to "Refresh",
        "difficulty" to "AI Difficulty",
        "easy" to "Easy",
        "medium" to "Normal",
        "hard" to "Hard",
        "expert" to "Expert",
        "nightmare" to "Nightmare",
        "insane" to "Insane",
        "ai_difficulties_tab" to "Difficulty Levels",
        "ai_personalities_tab" to "AI Personalities",
        "persona_rusher_title" to "The Aggressor",
        "persona_rusher_desc" to "Fast, ruthless, sprints straight for victory ⚡",
        "persona_defender_title" to "The Defender",
        "persona_defender_desc" to "Patient wall builder, waits for your mistakes 🛡️",
        "persona_chaotic_title" to "The Random",
        "persona_chaotic_desc" to "Unpredictable choices and chaotic walls 🎲",
        "persona_predictor_title" to "The Predictor",
        "persona_predictor_desc" to "Learns your favorite escape flank and seals it 🔮",
        "persona_trickster_title" to "The Trickster",
        "persona_trickster_desc" to "Deploys deceptive openings and bait corridors 🎭",
        "persona_tactician_title" to "The Tactician",
        "persona_tactician_desc" to "Calculates every step with precision 🧠",
        "time_control" to "Time Control",
        "infinite" to "Unlimited",
        "3_min" to "3 Minutes",
        "5_min" to "5 Minutes",
        "walls_count" to "Wall Count",
        "10_walls" to "10 Walls",
        "15_walls" to "15 Walls",
        "sound_effects" to "Sound Effects",
        "vibration" to "Haptic Feedback",
        "confirm_wall_toggle" to "Require Placement Confirmation",
        "show_legal_moves" to "Show Legal Move Indicators",
        "language" to "Language",
        "game_theme" to "Game Theme",
        "theme_cyber_neon" to "Cyber Neon (Main)",
        "theme_cyber_neon_desc" to "Glowing neon grid with electric cyan & magenta neon walls",
        "theme_deep_slate" to "Deep Slate (Classic)",
        "theme_deep_slate_desc" to "Calm dark slate canvas with modern blue & crimson accents",
        "theme_royal_emerald" to "Royal Emerald",
        "theme_royal_emerald_desc" to "Luxurious deep emerald board with royal brass gold walls",
        "theme_classic_wood" to "Classic Mahogany Wood",
        "theme_classic_wood_desc" to "Rich mahogany wooden finish with antique brass accents",
        "theme_obsidian_amber" to "Obsidian Amber",
        "theme_obsidian_amber_desc" to "Sleek charcoal obsidian with radiant amber gold tones",
        "username" to "Player Name",
        "save" to "Save",
        "settings_saved" to "Settings saved successfully",
        "total_games" to "Total Matches",
        "wins" to "Victories",
        "losses" to "Defeats",
        "win_rate" to "Win Rate",
        "streak" to "Winning Streak",
        "best_streak" to "Best Streak",
        "rating" to "Elo Rating",
        "total_walls" to "Walls Placed",
        "replay_title" to "Match Replay",
        "move_number" to "Move",
        "step_first" to "Start",
        "step_prev" to "Back",
        "step_play" to "Play",
        "step_pause" to "Pause",
        "step_next" to "Next",
        "step_last" to "End",
        "tutorial_title" to "Interactive Tutorial",
        "tut_step_1_title" to "1. Basic Movement",
        "tut_step_1_desc" to "Tap your pawn and step into any adjacent unblocked square. Your goal is to reach any square in the opponent's starting row!",
        "tut_step_2_title" to "2. Wall Placement",
        "tut_step_2_desc" to "Walls span 2 squares. Place them horizontally or vertically to lengthen your opponent's path.",
        "tut_step_3_title" to "3. Jumping Rivals",
        "tut_step_3_desc" to "When adjacent to an opponent, leap directly over them! If a wall is behind them, you can jump diagonally.",
        "tut_step_4_title" to "4. The Golden Rule: No Trapping",
        "tut_step_4_desc" to "You may never completely seal off a player from their goal. At least one open route must always exist!",
        "tut_step_5_title" to "5. Victory Condition",
        "tut_step_5_desc" to "The first player whose pawn touches any square in the opponent's starting row wins immediately!",
        "tut_step_6_title" to "6. Speed Race Mode 🏁",
        "tut_step_6_desc" to "Both players start side-by-side at the starting line. Sprint across the board to be the first to reach the emerald green finish line!",
        "tut_step_7_title" to "7. Quad Mode (4 Players) 🎯",
        "tut_step_7_desc" to "Four players enter from the 4 board borders. Everyone races toward the golden central tile (4,4) while navigating 4-way wall blockades!",
        "tut_step_8_title" to "8. Offline Local P2P 📡",
        "tut_step_8_desc" to "Play directly with nearby friends using Wi-Fi Hotspot or Bluetooth P2P without needing an internet connection!",
        "tut_step_9_title" to "9. Quests & Achievements 🏆",
        "tut_step_9_desc" to "Complete daily missions, earn experience points (XP), and unlock prestigious badges and achievements as you master tactical Quoridor!",

        // Real Network & P2P Keys
        "no_internet_title" to "No Internet Connection",
        "no_internet_msg" to "Online play requires an active internet connection. Please enable Wi-Fi or Mobile Data to play online.",
        "ok" to "OK",
        "p2p_mode_title" to "Play with a Nearby Friend",
        "p2p_mode_desc" to "Connect directly via Hotspot, Wi-Fi, or Bluetooth without needing external servers!",
        "p2p_method_wifi" to "Hotspot / Local Wi-Fi",
        "p2p_method_bt" to "Bluetooth P2P",
        "p2p_host_title" to "Host a Match (Player 1)",
        "p2p_join_title" to "Join Match as Guest (Player 2)",
        "p2p_host_btn" to "Start Hosting Server",
        "p2p_join_btn" to "Connect to Friend",
        "p2p_my_ip" to "Your Local IP Address:",
        "p2p_enter_ip" to "Enter Host IP Address:",
        "p2p_connecting" to "Connecting to friend...",
        "p2p_connected" to "Connected successfully!",
        "p2p_listening" to "Waiting for friend to connect on this network...",
        "p2p_disconnected_title" to "Friend Disconnected",
        "p2p_disconnected_msg" to "Connection with your friend was lost! The match has been terminated.",
        "p2p_bt_paired" to "Paired Devices (Phones & Tablets)",
        "p2p_bt_no_devices" to "No paired Bluetooth devices found. Please pair devices in Android settings first.",
        "p2p_bt_no_phones" to "No paired phones or tablets found. Non-gaming devices (headsets, watches, speakers) are automatically hidden.",
        "p2p_bt_phones_only" to "Phones & Tablets Only",
        "p2p_bt_all_devices" to "Show All Devices",
        "p2p_bt_host_listening" to "Bluetooth host active. Waiting for connection...",
        "p2p_bt_disabled" to "Bluetooth is currently turned off. Please turn it on in device settings.",
        "about" to "About WallRush",
        "developer_label" to "Programmed & Developed by:",
        "developer_name" to "Majd Anwar",
        "contact_label" to "Contact:",
        "contact_phone" to "+967 735 465 673",
        "email_label" to "Email:",
        "email_address" to "majd7772233@gmail.com",
        "phone_copied_dialer" to "Phone number copied & dialer opened",
        "email_copied" to "Email copied to clipboard",
        "app_full_desc" to "WallRush is an epic strategic mind game inspired by the legendary Quoridor. Outsmart your opponents, build walls to hinder their progress, and carve your path to victory!",
        "audio_haptics" to "Audio & Haptics",
        "gameplay_rules" to "Gameplay & Board",
        "reset_stats" to "Reset Statistics",
        "reset_stats_confirm" to "Are you sure you want to reset all match statistics? This action cannot be undone.",
        "waiting_room_title" to "Room Created - Waiting for Player",
        "waiting_room_desc" to "Your room is open. Waiting for someone to join...",
        "player_challenge_title" to "Player wants to play with you!",
        "accept" to "Accept",
        "reject" to "Reject",
        "searching_live_players" to "Searching for live players...",
        "matching_opponent" to "Matching with opponent...",
        "opponent_found" to "Opponent found! Initializing board...",
        "local_p1_victory_title" to "YOU WON THE MATCH!",
        "local_p2_victory_title" to "YOU WON THE MATCH!",
        "local_p1_loss_title" to "DEFEAT",
        "local_p2_loss_title" to "DEFEAT",
        "back_to_menu" to "Back to Main Menu",
        "race_mode" to "Race Mode 🏁",
        "race_mode_sub" to "Start on the same side and race to the finish line!",
        "quad_mode" to "Quad Mode (4 Players) 🎯",
        "quad_mode_sub" to "4 players entering from 4 sides racing to the board center!",
        "quad_center_goal" to "First to reach the center square wins!",
        "race_finish_line" to "Finish Line 🏁",
        "race_start_line" to "Starting Line 🚦",
        "steps_to_finish" to "steps to finish",
        "winner_player3" to "Player 3 (Green) Wins!",
        "winner_player4" to "Player 4 (Yellow) Wins!",
        "quad_pass_and_play" to "Quad Local (4 Players)",
        "quad_vs_ai" to "Quad vs 3 AI Bots",
        "race_vs_ai" to "Race vs AI",
        "race_pass_and_play" to "Race Local 2 Players",
        "classic_mode" to "Classic Match ⚔️",
        "classic_mode_sub" to "Reach the opposite edge of the board first!",
        "classic_mode_short" to "Classic ⚔️",
        "race_mode_short" to "Race 🏁",
        "quad_mode_short" to "Quad 4P 🎯",
        "select_game_mode" to "Select Game Mode",
        "ai_settings_title" to "Play vs AI Setup",
        "ai_setup_title" to "Play vs AI Setup",
        "select_difficulty" to "Difficulty Level",
        "walls_count" to "Walls Count",
        "time_control" to "Time Limit",
        "bt_supports_2p_only" to "Bluetooth connection supports 2 paired players (Classic & Race modes only)",
        "start_match" to "Start Match",
        "start_game" to "Start Game",
        "achievements_title" to "Achievements & Badges",
        "daily_challenges_title" to "Daily Quests",
        "daily_challenges_sub" to "Complete daily missions to earn XP & trophies",
        "claim_reward" to "Claim Reward",
        "claimed" to "Claimed",
        "resets_in" to "Resets in",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "start_challenge_now" to "Start Challenge 🚀",
        "random_challenge_title" to "Random Daily Challenge 🎲",
        "random_challenge_desc" to "The game selected the match parameters for you. Tap to start immediately!",
        "reroll_challenge" to "New Random Setup 🎲",
        "challenge_details" to "Challenge Specs",
        "challenge_mode" to "Mode",
        "challenge_opponent" to "Rival",
        "challenge_walls" to "Walls",
        "challenge_time" to "Time",
        "daily_random_title" to "Tactical Daily Quest 🎲",
        "daily_random_classic_desc" to "Defeat the chosen AI bot in Classic Quoridor battle!",
        "daily_random_race_desc" to "Outrun the chosen opponent in Speed Race Mode!",
        "daily_random_quad_desc" to "Conquer the 4-Player Quad arena against 3 AI rivals!",
        "ach_first_win_title" to "First Step to Glory",
        "ach_first_win_desc" to "Win your very first match",
        "ach_wins_5_title" to "Wall Warrior",
        "ach_wins_5_desc" to "Win 5 matches total",
        "ach_wins_20_title" to "Board Legend",
        "ach_wins_20_desc" to "Win 20 matches total",
        "ach_wins_50_title" to "Grandmaster Tactician",
        "ach_wins_50_desc" to "Win 50 matches total",
        "ach_wins_100_title" to "Quoridor Legend",
        "ach_wins_100_desc" to "Win 100 matches total",
        "ach_streak_3_title" to "Hot Streak",
        "ach_streak_3_desc" to "Achieve a 3-win streak",
        "ach_streak_5_title" to "Unstoppable",
        "ach_streak_5_desc" to "Achieve a 5-win streak",
        "ach_streak_10_title" to "Immortal Champion",
        "ach_streak_10_desc" to "Achieve a legendary 10-win streak",
        "ach_easy_ai_title" to "Rookie Training",
        "ach_easy_ai_desc" to "Defeat the AI on Easy difficulty",
        "ach_med_ai_title" to "Battle Hardened",
        "ach_med_ai_desc" to "Defeat the AI on Medium difficulty",
        "ach_hard_ai_title" to "Silicon Slayer",
        "ach_hard_ai_desc" to "Defeat the AI on Hard difficulty",
        "ach_expert_ai_title" to "Expert Slayer",
        "ach_expert_ai_desc" to "Defeat the AI on Expert difficulty",
        "ach_nightmare_ai_title" to "Nightmare Tamer",
        "ach_nightmare_ai_desc" to "Defeat the adaptive learning Nightmare AI",
        "ach_insane_ai_title" to "God of Logic",
        "ach_insane_ai_desc" to "Overcome the Insane Min-Max engine",
        "ach_defeat_rusher_title" to "Speedbreaker",
        "ach_defeat_rusher_desc" to "Defeat The Aggressor personality in battle",
        "ach_defeat_defender_title" to "Siege Breaker",
        "ach_defeat_defender_desc" to "Outplay The Defender personality",
        "ach_defeat_predictor_title" to "Mind Reader",
        "ach_defeat_predictor_desc" to "Win against The Predictor personality",
        "ach_defeat_trickster_title" to "Illusion Shatterer",
        "ach_defeat_trickster_desc" to "Outsmart The Trickster personality",
        "ach_defeat_tactician_title" to "Master Strategist",
        "ach_defeat_tactician_desc" to "Defeat The Tactician personality",
        "ach_wins_200_title" to "Immortal of Wall Rush",
        "ach_wins_200_desc" to "Reach 200 total victories",
        "ach_streak_15_title" to "Unstoppable Force",
        "ach_streak_15_desc" to "Achieve a monumental 15-win streak",
        "ach_walls_500_title" to "Supreme Mason",
        "ach_walls_500_desc" to "Place 500 tactical walls total",
        "ach_lightning_win_title" to "Sub-45s Blitz",
        "ach_lightning_win_desc" to "Win any match in under 45 seconds",
        "ach_clutch_win_title" to "Last-Second Hero",
        "ach_clutch_win_desc" to "Win with under 10 seconds remaining on your clock",
        "ach_daily_master_7_title" to "Devoted Challenger",
        "ach_daily_master_7_desc" to "Complete 7 Daily Challenges",
        "ach_flawless_title" to "Surgical Strike",
        "ach_flawless_desc" to "Win a match in 16 moves or fewer",
        "ach_comeback_title" to "Epic Comeback",
        "ach_comeback_desc" to "Win after an intense back-and-forth endgame",
        "ach_walls_10_title" to "First Bricks",
        "ach_walls_10_desc" to "Place 10 tactical walls total",
        "ach_walls_25_title" to "Tactical Mason",
        "ach_walls_25_desc" to "Place 25 walls total",
        "ach_walls_50_title" to "Barrier Architect",
        "ach_walls_50_desc" to "Place 50 walls total",
        "ach_walls_100_title" to "Labyrinth Master",
        "ach_walls_100_desc" to "Place 100 walls total",
        "ach_walls_250_title" to "Fortress Emperor",
        "ach_walls_250_desc" to "Place 250 walls total",
        "ach_minimalist_title" to "The Strategist",
        "ach_minimalist_desc" to "Win a match using 2 or fewer walls",
        "ach_wall_less_title" to "The Ghost Runner",
        "ach_wall_less_desc" to "Win a match without placing any walls",
        "ach_zero_waste_title" to "Total Depletion",
        "ach_zero_waste_desc" to "Win after placing all your available walls",
        "ach_maze_builder_title" to "Labyrinth King",
        "ach_maze_builder_desc" to "Place 8 or more walls in 3 separate matches",
        "ach_race_win_title" to "Speed Demon",
        "ach_race_win_desc" to "Win a match in Speed Race Mode",
        "ach_race_5_title" to "Velocity Overlord",
        "ach_race_5_desc" to "Win 5 matches in Race Mode",
        "ach_blitz_win_title" to "Lightning Reflex",
        "ach_blitz_win_desc" to "Win a rapid fast-paced match",
        "ach_timed_3m_title" to "Clock Conqueror",
        "ach_timed_3m_desc" to "Win 3 matches under 3-minute time control",
        "ach_p2p_title" to "Local Comrade",
        "ach_p2p_desc" to "Play a match via Hotspot or Bluetooth P2P",
        "ach_p2p_victor_title" to "Neighborhood Champion",
        "ach_p2p_victor_desc" to "Win 3 offline P2P matches against friends",
        "ach_quad_win_title" to "Quad Champion",
        "ach_quad_win_desc" to "Win a 4-Player Quad match",
        "ach_quad_master_title" to "Quad Grandmaster",
        "ach_quad_master_desc" to "Win 5 matches in 4-Player Quad Mode",
        "ach_lobby_title" to "Lobby Gladiator",
        "ach_lobby_desc" to "Win 3 matches in Public Rooms or Quick Match",
        "ach_pass_play_title" to "Couch Rivals",
        "ach_pass_play_desc" to "Play 3 Pass & Play matches on one device",
        "ach_night_owl_title" to "Midnight Tactician",
        "ach_night_owl_desc" to "Play a match between 12:00 AM and 5:00 AM",
        "ach_fashion_title" to "Persona Designer",
        "ach_fashion_desc" to "Customize your player username or avatar",
        "daily_win_title" to "Daily Glory",
        "daily_win_desc" to "Win 1 match today in any mode",
        "daily_ai_title" to "AI Sparring",
        "daily_ai_desc" to "Play 1 match against the AI",
        "daily_walls_title" to "Fortify The Board",
        "daily_walls_desc" to "Place 8 walls in your matches",
        "daily_race_title" to "Speed Sprint",
        "daily_race_desc" to "Play 1 match in Race Mode",
        "daily_quad_title" to "Quad Arena",
        "daily_quad_desc" to "Play 1 match in 4-Player Quad Mode",
        "tut_step_6_title" to "6. Race Mode",
        "tut_step_6_desc" to "Both players start side-by-side and sprint towards the green goal line across the board!",
        "tut_step_7_title" to "7. Quad Mode (4 Players)",
        "tut_step_7_desc" to "4 players clash from 4 sides! Maneuver your pawn and balance attack with multi-directional defense.",
        "tut_step_8_title" to "8. Offline P2P & Daily Quests",
        "tut_step_8_desc" to "Play with nearby friends offline via Wi-Fi or Bluetooth, and complete daily quests for bonus rewards!",
        "enable_smart_notifications" to "Smart Notifications",
        "notifications_enabled_desc" to "Daily quest alerts and achievement celebrations",
        "ai_expert" to "Expert",
        "ai_nightmare" to "Nightmare",
        "ai_insane" to "Insane",
        "personality_rusher" to "The Aggressor",
        "personality_defender" to "The Defender",
        "personality_chaotic" to "The Random",
        "personality_predictor" to "The Predictor",
        "personality_trickster" to "The Trickster",
        "personality_tactician" to "Tactical",
        "personality_speed_demon" to "Speed Demon",
        "personality_merciless" to "Merciless",
        "personality_architect" to "The Architect",
        "personality_counter_puncher" to "Counter-Puncher",
        "titles" to "Titles & Badges",
        "equipped_title" to "Equipped Title",
        "equip" to "Equip",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "level_editor" to "Level Editor",
        "custom_maps" to "Custom Maps",
        "create_level" to "Create New Level",
        "map_size" to "Grid Size",
        "place_obstacle" to "Pillars",
        "place_initial_wall" to "Preset Walls",
        "save_level" to "Save Level",
        "export_level" to "Export Code",
        "import_level" to "Import Code",
        "play_custom_level" to "Play Level",
        "powerups" to "Power-Ups",
        "energy" to "Energy",
        "time_rewind" to "Rewind Time",
        "time_rewind_sub" to "Rewinds game by 2 turns (AI Only)",
        "backup_restore" to "Save & Backup",
        "export_backup" to "Export Save File",
        "import_backup" to "Import Save File",
        "backup_success" to "Backup code generated and copied!",
        "restore_success" to "Save restored successfully!",
        "perfect_run" to "PERFECT RUN",
        "accuracy" to "Accuracy",
        "near_misses" to "Near Misses",
        "max_combo" to "Max Combo",
        "personal_ghost" to "Personal Ghost",
        "ghost_enabled" to "Show Best Run Ghost",
        "level_up" to "LEVEL UP!",
        "new_level" to "Level",
        "total_xp" to "Total XP",
        "unlocked_label" to "Unlocked",
        "challenge_reset_timer" to "Resets In",
        "filter_all" to "All",
        "filter_combat" to "Combat & Wins",
        "filter_tactics" to "Tactics & Walls",
        "filter_secret" to "Mastery & Special",
        "smart_notifications_title" to "Smart Daily Notifications",
        "smart_notifications_desc" to "Receive daily alerts for new challenges & milestones",
        "classic_mode" to "Classic Mode ♟️",
        "classic_mode_short" to "Classic ♟️",
        "race_mode_title" to "Race Mode 🏁",
        "quad_mode_title" to "4-Player Quad 🎯",
        "notif_daily_reminder_title" to "New Daily Challenge Ready!",
        "diff_easy" to "Easy",
        "diff_medium" to "Medium",
        "diff_hard" to "Hard"
    )

    private val ARABIC_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "اقطع طريق الخصم، وافتح طريقك",
        "quick_match" to "مباراة سريعة",
        "quick_match_sub" to "بحث فوري عن خصم حقيقي",
        "play_online" to "اللعب أونلاين",
        "play_online_sub" to "غرف عامة حية ومتجددة",
        "play_friend" to "العب مع صديق",
        "play_friend_sub" to "نقطة اتصال / واي فاي أو بلوتوث",
        "play_ai" to "اللعب ضد الذكاء الاصطناعي",
        "play_ai_sub" to "وضع التدريب التكتيكي",
        "pass_and_play" to "لعب محلي لشخصين",
        "pass_and_play_sub" to "لاعبان على نفس الشاشة",
        "race_mode" to "وضع السباق 🏁",
        "race_mode_sub" to "انطلاق من نفس الجهة والسباق نحو خط النهاية!",
        "quad_mode" to "الوضع الرباعي (٤ لاعبين) 🎯",
        "quad_mode_sub" to "٤ لاعبين من ٤ جهات يتسابقون نحو مربع المنتصف!",
        "quad_center_goal" to "أول من يصل إلى مربع المنتصف يفوز!",
        "race_finish_line" to "خط النهاية 🏁",
        "race_start_line" to "خط البداية 🚦",
        "steps_to_finish" to "خطوات للنهاية",
        "winner_player3" to "فاز اللاعب الثالث (الأخضر)!",
        "winner_player4" to "فاز اللاعب الرابع (الأصفر)!",
        "quad_pass_and_play" to "رباعي محلي (٤ لاعبين)",
        "quad_vs_ai" to "رباعي ضد ٣ روبوتات",
        "race_vs_ai" to "سباق ضد الذكاء الاصطناعي",
        "race_pass_and_play" to "سباق محلي لشخصين",
        "classic_mode" to "المباراة الكلاسيكية ⚔️",
        "classic_mode_sub" to "الوصول إلى الصف المقابل للخصم أولاً!",
        "classic_mode_short" to "كلاسيكي ⚔️",
        "race_mode_short" to "سباق 🏁",
        "quad_mode_short" to "رباعي ٤ لاعبين 🎯",
        "select_game_mode" to "اختر وضع اللعبة",
        "ai_settings_title" to "إعدادات اللعب ضد الذكاء الاصطناعي",
        "ai_setup_title" to "إعدادات اللعب ضد الذكاء الاصطناعي",
        "select_difficulty" to "مستوى الصعوبة",
        "walls_count" to "عدد الجدران",
        "time_control" to "الوقت المحدد",
        "bt_supports_2p_only" to "اتصال البلوتوث يدعم جهازين مقترنين فقط (الوضع الكلاسيكي ووضع السباق)",
        "start_match" to "ابدأ المباراة",
        "start_game" to "ابدأ اللعبة",
        "how_to_play" to "كيفية اللعب",
        "how_to_play_sub" to "القواعد والتدريب التفاعلي",
        "leaderboard" to "لوحة الصدارة",
        "profile" to "الملف الشخصي",
        "settings" to "الإعدادات",
        "match_history" to "سجل المباريات",
        "replays" to "إعادة المباريات",
        "searching_opponent" to "جارٍ البحث عن خصم متصل...",
        "cancel" to "إلغاء",
        "ready" to "جاهز",
        "countdown" to "تبدأ المباراة خلال",
        "your_turn" to "دورك الآن",
        "opponents_turn" to "دور الخصم الآن",
        "walls_remaining" to "الجدران المتبقية",
        "place_wall" to "وضع جدار",
        "cancel_wall" to "إلغاء",
        "rotate_wall" to "تدوير (أفقي / رأسي)",
        "confirm_wall" to "تثبيت الجدار",
        "horizontal" to "أفقي",
        "vertical" to "رأسي",
        "resign" to "استسلام",
        "resign_confirm_title" to "هل ترغب في الاستسلام؟",
        "resign_confirm_desc" to "هل أنت متأكد من رغبتك في إعلان الانسحاب وخسارة الجولة؟",
        "rematch" to "إعادة اللعب",
        "menu" to "القائمة الرئيسية",
        "you_win" to "انتصار ساحق!",
        "you_lose" to "هزيمة",
        "draw" to "تعادل",
        "winner_player1" to "فاز اللاعب الأول!",
        "winner_player2" to "فاز اللاعب الثاني!",
        "goal_reached" to "وصل بقطعته إلى خط نهاية الخصم!",
        "time_out" to "فوز بانتهاء وقت الخصم!",
        "resigned_reason" to "استسلم الخصم وأعلن انسحابه!",
        "disconnected_reason" to "انقطع اتصال الخصم! انتهت المباراة.",
        "create_room" to "إنشاء غرفة",
        "join_room" to "انضمام لغرفة",
        "enter_room_code" to "أدخل عنوان IP للمضيف أو الرمز",
        "room_code" to "رمز الغرفة",
        "copy_code" to "نسخ الرمز",
        "share_code" to "مشاركة الرمز",
        "waiting_for_player" to "بانتظار انضمام الخصم...",
        "room_full" to "الغرفة ممتلئة بالكامل",
        "room_not_found" to "تعذر العثور على الغرفة",
        "public_rooms" to "الغرف العامة المباشرة",
        "no_rooms_available" to "لا توجد غرف متاحة حالياً. أنشئ غرفة الآن!",
        "refresh" to "تحديث الغرف",
        "difficulty" to "مستوى الذكاء الاصطناعي",
        "easy" to "سهل",
        "medium" to "متوسط",
        "hard" to "صعب",
        "expert" to "خبير",
        "nightmare" to "كابوس",
        "insane" to "مجنون",
        "ai_difficulties_tab" to "مستويات الصعوبة",
        "ai_personalities_tab" to "شخصيات AI",
        "persona_rusher_title" to "المهاجم (The Aggressor)",
        "persona_rusher_desc" to "سريع وهجومي، اندفاع مباشر نحو الفوز ⚡",
        "persona_defender_title" to "المدافع (The Defender)",
        "persona_defender_desc" to "صبور، يبني الأسوار وينتظر أخطاءك 🛡️",
        "persona_chaotic_title" to "العشوائي (The Random)",
        "persona_chaotic_desc" to "حركات غير متوقعة وتشتيت للمسارات 🎲",
        "persona_predictor_title" to "المتنبئ (The Predictor)",
        "persona_predictor_desc" to "يتعلم أسلوبك في الهروب ويغلق مسارك 🔮",
        "persona_trickster_title" to "المخادع (The Trickster)",
        "persona_trickster_desc" to "يستخدم فخاخاً وهمية وممرات مضللة 🎭",
        "persona_tactician_title" to "التكتيكي (The Tactician)",
        "persona_tactician_desc" to "حسابات دقيقة لأقصر مسار ممكن 🧠",
        "time_control" to "نظام الوقت",
        "infinite" to "غير محدود",
        "3_min" to "3 دقائق",
        "5_min" to "5 دقائق",
        "walls_count" to "عدد الجدران لكل لاعب",
        "10_walls" to "10 جدران",
        "15_walls" to "15 جداراً",
        "sound_effects" to "المؤثرات الصوتية",
        "vibration" to "الاهتزاز اللمسي",
        "confirm_wall_toggle" to "طلب تأكيد قبل تثبيت الجدار",
        "show_legal_moves" to "إظهار مؤشرات النقلات المتاحة",
        "language" to "اللغة",
        "game_theme" to "ثيم اللعبة",
        "theme_cyber_neon" to "نيون سايبورغ (الرئيسي)",
        "theme_cyber_neon_desc" to "مظهر نيون متوهج بخطوط شبكية إلكترونية وجدران فسفورية مشعة",
        "theme_deep_slate" to "ديب سليت (الكلاسيكي المحسن)",
        "theme_deep_slate_desc" to "مظهر رمادي داكن هادئ ومريح للعين مع إضاءة زرقاء وحمراء",
        "theme_royal_emerald" to "الزمرد الملكي",
        "theme_royal_emerald_desc" to "مظهر فاخر بدرجات الزمرد الأخضر مع جدران ذهبية براقة",
        "theme_classic_wood" to "الخشب الكلاسيكي",
        "theme_classic_wood_desc" to "مظهر خشبي عريق من خشب الماهوجني الداكن ولمسات نحاسية",
        "theme_obsidian_amber" to "الأوبسيديان والكهرمان",
        "theme_obsidian_amber_desc" to "مظهر صخري داكن فخم بتفاصيل الكهرمان الدافئ والبنفسجي",
        "username" to "اسم اللاعب",
        "save" to "حفظ التغييرات",
        "settings_saved" to "تم حفظ الإعدادات بنجاح",
        "total_games" to "المباريات الملعوبة",
        "wins" to "الانتصارات",
        "losses" to "الهزائم",
        "win_rate" to "نسبة الفوز",
        "streak" to "سلسلة الانتصارات الحالية",
        "best_streak" to "أفضل سلسلة انتصارات",
        "rating" to "نقاط التصنيف (Rating)",
        "total_walls" to "الجدران المشيدة",
        "replay_title" to "إعادة عرض المباراة",
        "move_number" to "النقلة",
        "step_first" to "البداية",
        "step_prev" to "السابقة",
        "step_play" to "تشغيل",
        "step_pause" to "إيقاف مؤقت",
        "step_next" to "التالية",
        "step_last" to "النهاية",
        "tutorial_title" to "التدريب التفاعلي",
        "tut_step_1_title" to "1. الحركة الأساسية",
        "tut_step_1_desc" to "انقر على قطعتك ثم تحرك إلى أي خانة مجاورة غير محجوبة بحاجز. هدفك الأسمى هو الوصول إلى أي خانة في صف بداية الخصم المقابل!",
        "tut_step_2_title" to "2. وضع الجدران العازلة",
        "tut_step_2_desc" to "طول كل جدار خانتان كاملتان. ضعه أفقياً أو رأسياً لإطالة مسار الخصم وإجباره على الالتفاف وتضييع نقلاته.",
        "tut_step_3_title" to "3. القفز فوق المنافس",
        "tut_step_3_desc" to "عندما تتواجه قطعتك مع الخصم وجهاً لوجه، يمكنك القفز مباشرة فوقه! وإذا كان خلفه جدار عازل، يسمح لك بالقفز قطرياً.",
        "tut_step_4_title" to "4. القاعدة الذهبية: حظر الحصار الكامل",
        "tut_step_4_desc" to "يُحظر تماماً وضع جدار يغلق جميع المسارات المؤدية لخط النهاية أمام أي لاعب. يجب أن يظل هناك مسار سالك واحد على الأقل دائماً!",
        "tut_step_5_title" to "5. شروط الفوز",
        "tut_step_5_desc" to "أول لاعب تلمس قطعته أي خانة في خط بداية الخصم يفوز فوراً بالمباراة ويتوج بطلاً!",
        "tut_step_6_title" to "6. سباق السرعة (Race Mode) 🏁",
        "tut_step_6_desc" to "ينطلق اللاعبان جنباً إلى جنب من خط البداية! تسابق للوصول أولاً إلى خط النهاية الأخضر في قمة اللوحة مع بناء حواجز تكتيكية لتعطيل الخصم.",
        "tut_step_7_title" to "7. وضع 4 لاعبين (Quad Mode) 🎯",
        "tut_step_7_desc" to "4 لاعبين يبدأ كل منهم من أحد جوانب اللوحة الأربعة. الهدف هو الوصول أولاً إلى خانة الهدف الذهبية في المنتصف (4,4) وسط صراع الجدران من 4 اتجاهات!",
        "tut_step_8_title" to "8. اللعب بدون إنترنت (P2P) 📡",
        "tut_step_8_desc" to "العب مباشرة مع أصدقائك عبر البلوتوث الحقيقي أو نقطة الاتصال المحلية (Hotspot) بدون الحاجة إلى باقة أو إنترنت على الإطلاق!",
        "tut_step_9_title" to "9. المهام اليومية والإنجازات 🏆",
        "tut_step_9_desc" to "أنجز التحديات اليومية المتجددة لكسب نقاط الخبرة (XP) وفتح أوسمة الإنجازات والارتقاء في مستواك التكتيكي من مبتدئ إلى سيد الأساطير!",

        // Real Network & P2P Keys (اللعب ضد صديق بالبلوتوث ونقطة الاتصال والإنترنت)
        "no_internet_title" to "لا يتوفر اتصال بالإنترنت",
        "no_internet_msg" to "يتطلب وضع اللعب عبر الإنترنت اتصالاً نشطاً بالشبكة. يرجى تفعيل Wi-Fi أو بيانات الهاتف للبحث عن لاعبين والانضمام للغرف العامة.",
        "ok" to "حسناً",
        "p2p_mode_title" to "اللعب المباشر مع صديق",
        "p2p_mode_desc" to "اتصال حقيقي مباشر بين جهازين باستخدام نقطة الاتصال (Hotspot)، أو شبكة Wi-Fi محلية، أو البلوتوث الفعلي بدون الحاجة لإنترنت!",
        "p2p_method_wifi" to "نقطة اتصال (Hotspot) / Wi-Fi",
        "p2p_method_bt" to "بلوتوث (Bluetooth P2P)",
        "p2p_host_title" to "إنشاء استضافة (اللاعب 1)",
        "p2p_join_title" to "انضمام إلى الصديق (اللاعب 2)",
        "p2p_host_btn" to "بدء استضافة الغرفة",
        "p2p_join_btn" to "اتصال بجهاز الصديق",
        "p2p_my_ip" to "عنوان IP لجهازك:",
        "p2p_enter_ip" to "أدخل عنوان IP للمضيف:",
        "p2p_connecting" to "جارٍ الاتصال بجهاز الصديق...",
        "p2p_connected" to "تم الاتصال بنجاح! تبدأ المباراة الآن...",
        "p2p_listening" to "في انتظار انضمام الصديق عبر الشبكة...",
        "p2p_disconnected_title" to "انقطع الاتصال بالصديق!",
        "p2p_disconnected_msg" to "تم فقدان الاتصال بين الجهازين! توقفت اللعبة فوراً بسبب إيقاف الاتصال أو انقطاع الشبكة/البلوتوث.",
        "p2p_bt_paired" to "الأجهزة المتوافقة (الهواتف والأجهزة اللوحية)",
        "p2p_bt_no_devices" to "لا توجد أجهزة بلوتوث مقترنة. يرجى إقران الجهازين أولاً من إعدادات البلوتوث في الهاتف.",
        "p2p_bt_no_phones" to "لم يتم العثور على هواتف مقترنة. تم إخفاء السماعات والساعات والأجهزة غير المتوافقة تلقائياً.",
        "p2p_bt_phones_only" to "الهواتف فقط (مفلترة)",
        "p2p_bt_all_devices" to "عرض كل الأجهزة",
        "p2p_bt_host_listening" to "خادم البلوتوث قيد الانتظار... اطلب من صديقك الاتصال بجهازك الآن.",
        "p2p_bt_disabled" to "البلوتوث غير مفعّل حالياً على جهازك. يرجى تشغيله للمتابعة.",
        "about" to "عن التطبيق والمعلومات",
        "developer_label" to "برمجة وتطوير:",
        "developer_name" to "مجد أنور",
        "contact_label" to "للتواصل:",
        "contact_phone" to "+967 735 465 673",
        "email_label" to "البريد الإلكتروني:",
        "email_address" to "majd7772233@gmail.com",
        "phone_copied_dialer" to "تم فتح لوحة الاتصال ونسخ الرقم",
        "email_copied" to "تم نسخ البريد الإلكتروني إلى الحافظة",
        "app_full_desc" to "لعبة WallRush هي معركة ذهنية وتكتيكية ملحمية مستوحاة من لعبة كوريدور العالمية الشهيرة. اخدع خصومك، ابنِ الجدران العازلة لقطع مسارهم، وشق طريقك نحو النصر!",
        "audio_haptics" to "الصوتيات والاهتزاز",
        "gameplay_rules" to "أسلوب اللعب واللوحة",
        "reset_stats" to "إعادة تعيين الإحصائيات",
        "reset_stats_confirm" to "هل أنت متأكد من رغبتك في تصفير جميع الإحصائيات؟ لا يمكن التراجع عن هذا الإجراء.",
        "waiting_room_title" to "تم إنشاء الغرفة - بانتظار لاعب",
        "waiting_room_desc" to "غرفتك مفتوحة الآن وفي انتظار انضمام أي منافس...",
        "player_challenge_title" to "هناك لاعب يريد أن يلعب معك!",
        "accept" to "قبول",
        "reject" to "رفض",
        "searching_live_players" to "جارٍ البحث عن لاعبين نشطين...",
        "matching_opponent" to "جارٍ مطابقة المنافس...",
        "opponent_found" to "تم العثور على خصم! تهيئة رقعة اللعب...",
        "local_p1_victory_title" to "ألف مبروك! لقد فزت بالمباراة! 🏆",
        "local_p2_victory_title" to "ألف مبروك! لقد فزت بالمباراة! 🏆",
        "local_p1_loss_title" to "حظاً أوفر في المرة القادمة! (هزيمة)",
        "local_p2_loss_title" to "حظاً أوفر في المرة القادمة! (هزيمة)",
        "back_to_menu" to "العودة للشاشة الرئيسية",
        "achievements_title" to "الإنجازات والأوسمة",
        "daily_challenges_title" to "التحديات اليومية",
        "daily_challenges_sub" to "أنجز مهامك اليومية واكسب نقاط الترتيب والخبرة",
        "claim_reward" to "استلام الجائزة",
        "claimed" to "تم الاستلام",
        "resets_in" to "يتجدد خلال",
        "unlocked" to "مكتمل",
        "locked" to "مقفل",
        "start_challenge_now" to "بدء التحدي مباشرة 🚀",
        "random_challenge_title" to "التحدي اليومي العشوائي 🎲",
        "random_challenge_desc" to "قام النظام باختيار تفاصيل ورقعة التحدي تلقائياً. اضغط للبدء واللعب فوراً!",
        "reroll_challenge" to "تحدي عشوائي جديد 🎲",
        "challenge_details" to "تفاصيل التحدي",
        "challenge_mode" to "الوضع",
        "challenge_opponent" to "المنافس",
        "challenge_walls" to "الجدران",
        "challenge_time" to "الوقت",
        "daily_random_title" to "التحدي التكتيكي اليومي 🎲",
        "daily_random_classic_desc" to "اهزم الروبوت المحدد في المعركة الكلاسيكية!",
        "daily_random_race_desc" to "اسبق المنافس المحدد نحو خط النهاية في سباق السرعة!",
        "daily_random_quad_desc" to "سيطر على الساحة الرباعية واهزم 3 روبوتات ذكاء اصطناعي!",
        "ach_first_win_title" to "أول خطوة نحو المجد",
        "ach_first_win_desc" to "الفوز بأول مباراة لك في اللعبة",
        "ach_wins_5_title" to "محارب الجدران",
        "ach_wins_5_desc" to "تحقيق الفوز في 5 مباريات",
        "ach_wins_20_title" to "أسطورة الرقعة",
        "ach_wins_20_desc" to "تحقيق الفوز في 20 مباراة",
        "ach_wins_50_title" to "سيد التكتيك الكبير",
        "ach_wins_50_desc" to "تحقيق الفوز في 50 مباراة",
        "ach_wins_100_title" to "أسطورة كوريدور الخالدة",
        "ach_wins_100_desc" to "تحقيق الفوز في 100 مباراة تاريخية",
        "ach_streak_3_title" to "سلسلة نارية",
        "ach_streak_3_desc" to "تحقيق سلسلة 3 انتصارات متتالية",
        "ach_streak_5_title" to "لا يُقهر",
        "ach_streak_5_desc" to "تحقيق سلسلة 5 انتصارات متتالية",
        "ach_streak_10_title" to "البطل الأسطوري الخارق",
        "ach_streak_10_desc" to "تحقيق سلسلة 10 انتصارات متتالية أسطورية",
        "ach_easy_ai_title" to "تدريب المبتدئين",
        "ach_easy_ai_desc" to "الفوز على الذكاء الاصطناعي بمستوى سهل",
        "ach_med_ai_title" to "محارب متمرس",
        "ach_med_ai_desc" to "الفوز على الذكاء الاصطناعي بمستوى متوسط",
        "ach_hard_ai_title" to "قاهر الذكاء الاصطناعي",
        "ach_hard_ai_desc" to "الفوز على الذكاء الاصطناعي بمستوى صعب",
        "ach_expert_ai_title" to "قاهر الخبراء",
        "ach_expert_ai_desc" to "الفوز على الذكاء الاصطناعي بمستوى خبير",
        "ach_nightmare_ai_title" to "مروض الكوابيس",
        "ach_nightmare_ai_desc" to "الفوز على ذكاء الكابوس المتكيف والمتعلم",
        "ach_insane_ai_title" to "إله المنطق والحساب",
        "ach_insane_ai_desc" to "التغلب على ذكاء المين-ماكس المجنون الخارق",
        "ach_defeat_rusher_title" to "كاسر السرعة",
        "ach_defeat_rusher_desc" to "الفوز على شخصية المهاجم المندفع",
        "ach_defeat_defender_title" to "كاسر الحصار",
        "ach_defeat_defender_desc" to "التفوق على شخصية المدافع الحصين",
        "ach_defeat_predictor_title" to "قارئ الأفكار",
        "ach_defeat_predictor_desc" to "هزيمة شخصية المتنبئ التي تقرأ أسلوبك",
        "ach_defeat_trickster_title" to "محطم الأوهام",
        "ach_defeat_trickster_desc" to "كشف حيل وفخاخ شخصية المخادع",
        "ach_defeat_tactician_title" to "العقل التكتيكي الأعظم",
        "ach_defeat_tactician_desc" to "التغلب على شخصية التكتيكي في معركة هندسية",
        "ach_wins_200_title" to "أسطورة وول رش الخالدة",
        "ach_wins_200_desc" to "تحقيق 200 انتصار تاريخي",
        "ach_streak_15_title" to "القوة القاهرة",
        "ach_streak_15_desc" to "تحقيق سلسلة 15 انتصاراً متتالياً بلا هزيمة",
        "ach_walls_500_title" to "البناء الأعظم",
        "ach_walls_500_desc" to "وضع 500 جدار تكتيكي في المباريات",
        "ach_lightning_win_title" to "البرق الخاطف",
        "ach_lightning_win_desc" to "الفوز بأي مباراة في أقل من 45 ثانية",
        "ach_clutch_win_title" to "بطل الثواني الأخيرة",
        "ach_clutch_win_desc" to "الفوز والمتبقي في ساعتك أقل من 10 ثوانٍ",
        "ach_daily_master_7_title" to "البطل المتفاني",
        "ach_daily_master_7_desc" to "إكمال 7 تحديات يومية",
        "ach_flawless_title" to "ضربة جراحية خاطفة",
        "ach_flawless_desc" to "الفوز في مباراة خلال 16 نقلة أو أقل",
        "ach_comeback_title" to "عودة الملوك الأسطورية",
        "ach_comeback_desc" to "الفوز بمباراة حماسية في الأمتار الأخيرة",
        "ach_walls_10_title" to "أحجار البداية",
        "ach_walls_10_desc" to "وضع 10 جدران تكتيكية",
        "ach_walls_25_title" to "بنّاء الممرات",
        "ach_walls_25_desc" to "وضع 25 جداراً تكتيكياً",
        "ach_walls_50_title" to "مهندس الحصون",
        "ach_walls_50_desc" to "وضع 50 جداراً تكتيكياً",
        "ach_walls_100_title" to "سيد المتاهات",
        "ach_walls_100_desc" to "وضع 100 جدار تكتيكي",
        "ach_walls_250_title" to "إمبراطور القلاع والأسوار",
        "ach_walls_250_desc" to "وضع 250 جداراً تكتيكياً",
        "ach_minimalist_title" to "العقل المدبر النقي",
        "ach_minimalist_desc" to "الفوز بمباراة دون استخدام أكثر من جدارين",
        "ach_wall_less_title" to "العداء الشبح",
        "ach_wall_less_desc" to "الفوز بمباراة كاملة دون وضع أي جدار إطلاقاً!",
        "ach_zero_waste_title" to "استنزاف الترسانة",
        "ach_zero_waste_desc" to "الفوز بعد استهلاك كافة الجدران المتاحة لك",
        "ach_maze_builder_title" to "ناسج المتاهات",
        "ach_maze_builder_desc" to "وضع 8 جدران أو أكثر في 3 مباريات مختلفة",
        "ach_race_win_title" to "سهم السباق",
        "ach_race_win_desc" to "الفوز في وضع سباق السرعة",
        "ach_race_5_title" to "سيد سباقات السرعة",
        "ach_race_5_desc" to "الفوز في 5 مباريات بوضع السباق",
        "ach_blitz_win_title" to "رد الفعل الخاطف",
        "ach_blitz_win_desc" to "الفوز في مباراة سريعة وحاسمة",
        "ach_timed_3m_title" to "قاهر عقارب الساعة",
        "ach_timed_3m_desc" to "الفوز في 3 مباريات بنظام وقت 3 دقائق",
        "ach_p2p_title" to "رفيق المعارك المحلية",
        "ach_p2p_desc" to "لعب مباراة عبر نقطة الاتصال أو البلوتوث",
        "ach_p2p_victor_title" to "بطل الحارة والديوانية",
        "ach_p2p_victor_desc" to "الفوز في 3 مباريات بدون نت ضد أصدقائك",
        "ach_quad_win_title" to "بطل الساحة الرباعية",
        "ach_quad_win_desc" to "الفوز في معركة الـ 4 لاعبين الرباعية",
        "ach_quad_master_title" to "أستاذ المعارك الرباعية",
        "ach_quad_master_desc" to "الفوز في 5 معارك بالوضع الرباعي",
        "ach_lobby_title" to "مصارع الغرف العامة",
        "ach_lobby_desc" to "الفوز في 3 مباريات في الغرف العامة أو السريعة",
        "ach_pass_play_title" to "منافسات الشاشة الواحدة",
        "ach_pass_play_desc" to "لعب 3 مباريات محلية مع صديق على نفس الجهاز",
        "ach_night_owl_title" to "تكتيكي منتصف الليل",
        "ach_night_owl_desc" to "لعب مباراة بين الساعة 12:00 ليلاً و 5:00 فجراً",
        "ach_fashion_title" to "خبير الأناقة والتخصيص",
        "ach_fashion_desc" to "تخصيص اسم اللاعب وتغيير الصورة الرمزية (Avatar)",
        "daily_win_title" to "المجد اليومي",
        "daily_win_desc" to "اربح مباراة واحدة اليوم في أي وضع",
        "daily_ai_title" to "تحدي الروبوت",
        "daily_ai_desc" to "العب مباراة واحدة ضد الذكاء الاصطناعي",
        "daily_walls_title" to "تحصين الرقعة",
        "daily_walls_desc" to "ضع 8 جدران تكتيكية خلال مبارياتك اليوم",
        "daily_race_title" to "سباق السرعة",
        "daily_race_desc" to "العب مباراة واحدة في وضع السباق السريع",
        "daily_quad_title" to "المعركة الرباعية",
        "daily_quad_desc" to "العب مباراة واحدة في وضع الـ 4 لاعبين الرباعي",
        "tut_step_6_title" to "6. وضع السباق السريع",
        "tut_step_6_desc" to "كلا اللاعبين يبدآن متجاورين في نفس الصف، ويتسابقان نحو خط النهاية الأخضر في الطرف المقابل مع استخدام الجدران للعرقلة!",
        "tut_step_7_title" to "7. المعركة الرباعية (4 لاعبين)",
        "tut_step_7_desc" to "4 لاعبين من 4 جهات مختلفة! هدف كل لاعب الوصول إلى الجهة المقابلة مع بناء متاهات جدران رباعية معقدة.",
        "tut_step_8_title" to "8. اللعب بدون نت والتحديات اليومية",
        "tut_step_8_desc" to "العب مع أصدقائك بدون إنترنت عبر نقطة الاتصال Wi-Fi أو البلوتوث المباشر، وأنجز التحديات اليومية لجوائز إضافية!",
        "enable_smart_notifications" to "إشعارات التحديات الذكية",
        "notifications_enabled_desc" to "تلقي تنبيهات يومية بالتحديات الجديدة والاحتفال بالإنجازات",
        "ai_expert" to "خبير",
        "ai_nightmare" to "كابوس",
        "ai_insane" to "جنوني",
        "personality_rusher" to "المهاجم الشرس",
        "personality_defender" to "المدافع الحذر",
        "personality_chaotic" to "العشوائي غير المتوقع",
        "personality_predictor" to "المتنبئ الخارق",
        "personality_trickster" to "المخادع الماكر",
        "personality_tactician" to "التكتيكي المحنك",
        "personality_speed_demon" to "شيطان السرعة",
        "personality_merciless" to "عديم الرحمة",
        "personality_architect" to "المهندس المعماري",
        "personality_counter_puncher" to "الملاكم المتربص",
        "titles" to "الألقاب والشارات",
        "equipped_title" to "اللقب المجهز",
        "equip" to "تجهيز",
        "unlocked" to "مفتوح",
        "locked" to "مقفل",
        "level_editor" to "محرر المراحل",
        "custom_maps" to "المراحل المخصصة",
        "create_level" to "تصميم مرحلة جديدة",
        "map_size" to "أبعاد الساحة",
        "place_obstacle" to "أعمدة صخرية",
        "place_initial_wall" to "جدران مبدئية",
        "save_level" to "حفظ المرحلة",
        "export_level" to "تصدير كود المرحلة",
        "import_level" to "استيراد مرحلة",
        "play_custom_level" to "بدء اللعب",
        "powerups" to "القدرات التكتيكية",
        "energy" to "الطاقة",
        "time_rewind" to "إرجاع الزمن",
        "time_rewind_sub" to "الرجوع خطوتين للوراء (طور AI فقط)",
        "backup_restore" to "النسخ الاحتياطي والحفظ",
        "export_backup" to "تصدير ملف الحفظ",
        "import_backup" to "استيراد ملف الحفظ",
        "backup_success" to "تم إنشاء كود الحفظ ونسخه بنجاح!",
        "restore_success" to "تمت استعادة ملف الحفظ بنجاح!",
        "perfect_run" to "جولة مثالية خارقة",
        "accuracy" to "الدقة التكتيكية",
        "near_misses" to "مراوغات قريبة",
        "max_combo" to "أعلى كومبو",
        "personal_ghost" to "الشبح الذاتي",
        "ghost_enabled" to "إظهار شبح أفضل جولة لك",
        "level_up" to "ارتقاء في المستوى!",
        "new_level" to "المستوى",
        "total_xp" to "إجمالي نقاط الخبرة",
        "unlocked_label" to "مكتمل",
        "challenge_reset_timer" to "يتجدد خلال",
        "filter_all" to "الكل",
        "filter_combat" to "المعارك والانتصارات",
        "filter_tactics" to "التكتيك والجدران",
        "filter_secret" to "الإتقان والتحديات الخاصة",
        "smart_notifications_title" to "تنبيهات التحديات الذكية",
        "smart_notifications_desc" to "تلقي تنبيهات يومية بالتحديات الجديدة والاحتفال بالإنجازات",
        "classic_mode" to "الوضع الكلاسيكي ♟️",
        "classic_mode_short" to "كلاسيكي ♟️",
        "race_mode_title" to "وضع السباق السريع 🏁",
        "quad_mode_title" to "الوضع الرباعي (٤ لاعبين) 🎯",
        "notif_daily_reminder_title" to "تحدي يومي جديد متاح الآن!",
        "diff_easy" to "سهل",
        "diff_medium" to "متوسط",
        "diff_hard" to "صعب"
    )
}
