package com.example.wallrush.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    ARABIC("ar", "Arabic", "العربية")
}

object Strings {
    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.ARABIC) ARABIC_MAP else ENGLISH_MAP
        return dict[key] ?: ENGLISH_MAP[key] ?: key
    }

    private val ENGLISH_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "Block their way, clear yours",
        "quick_match" to "Quick Match",
        "quick_match_sub" to "Find a live opponent",
        "play_online" to "Play Online",
        "play_online_sub" to "Live Public Rooms",
        "play_friend" to "Play a Friend",
        "play_friend_sub" to "Hotspot / Wi-Fi & Bluetooth",
        "play_ai" to "Play Against AI",
        "play_ai_sub" to "Strategic Practice Mode",
        "pass_and_play" to "Pass & Play",
        "pass_and_play_sub" to "2 Players on 1 Device",
        "how_to_play" to "How to Play",
        "how_to_play_sub" to "Rules & Interactive Tutorial",
        "leaderboard" to "Leaderboard",
        "profile" to "Profile",
        "settings" to "Settings",
        "match_history" to "Match History",
        "replays" to "Replays",
        "searching_opponent" to "Searching for live opponent...",
        "cancel" to "Cancel",
        "ready" to "Ready",
        "countdown" to "Match Starts In",
        "your_turn" to "YOUR TURN",
        "opponents_turn" to "OPPONENT'S TURN",
        "walls_remaining" to "Walls Remaining",
        "place_wall" to "Place Wall",
        "cancel_wall" to "Cancel",
        "rotate_wall" to "Rotate (H/V)",
        "confirm_wall" to "Confirm Placement",
        "horizontal" to "Horizontal",
        "vertical" to "Vertical",
        "resign" to "Resign",
        "resign_confirm_title" to "Surrender Match?",
        "resign_confirm_desc" to "Are you sure you want to forfeit this match?",
        "rematch" to "Rematch",
        "menu" to "Main Menu",
        "you_win" to "VICTORY!",
        "you_lose" to "DEFEAT",
        "draw" to "DRAW",
        "winner_player1" to "Player 1 Wins!",
        "winner_player2" to "Player 2 Wins!",
        "goal_reached" to "Reached the opponent's baseline!",
        "time_out" to "Won on time expiration!",
        "resigned_reason" to "Opponent conceded victory!",
        "disconnected_reason" to "Opponent disconnected! Match terminated.",
        "create_room" to "Create Room",
        "join_room" to "Join Room",
        "enter_room_code" to "Enter Host IP or Room Code",
        "room_code" to "Room Code",
        "copy_code" to "Copy Code",
        "share_code" to "Share Code",
        "waiting_for_player" to "Waiting for opponent to join...",
        "room_full" to "Room is full",
        "room_not_found" to "Room not found",
        "public_rooms" to "Public Live Rooms",
        "no_rooms_available" to "No public rooms available. Create one!",
        "refresh" to "Refresh",
        "difficulty" to "AI Difficulty",
        "easy" to "Easy",
        "medium" to "Medium",
        "hard" to "Expert",
        "time_control" to "Time Control",
        "infinite" to "Unlimited",
        "3_min" to "3 Minutes",
        "5_min" to "5 Minutes",
        "walls_count" to "Wall Count",
        "10_walls" to "10 Walls",
        "15_walls" to "15 Walls",
        "sound_effects" to "Sound Effects",
        "vibration" to "Haptic Feedback",
        "confirm_wall_toggle" to "Require Placement Confirmation",
        "show_legal_moves" to "Show Legal Move Indicators",
        "language" to "Language",
        "game_theme" to "Game Theme",
        "theme_cyber_neon" to "Cyber Neon (Main)",
        "theme_cyber_neon_desc" to "Glowing neon grid with electric cyan & magenta neon walls",
        "theme_deep_slate" to "Deep Slate (Classic)",
        "theme_deep_slate_desc" to "Calm dark slate canvas with modern blue & crimson accents",
        "theme_royal_emerald" to "Royal Emerald",
        "theme_royal_emerald_desc" to "Luxurious deep emerald board with royal brass gold walls",
        "theme_classic_wood" to "Classic Mahogany Wood",
        "theme_classic_wood_desc" to "Rich mahogany wooden finish with antique brass accents",
        "theme_obsidian_amber" to "Obsidian Amber",
        "theme_obsidian_amber_desc" to "Sleek charcoal obsidian with radiant amber gold tones",
        "username" to "Player Name",
        "save" to "Save",
        "settings_saved" to "Settings saved successfully",
        "total_games" to "Total Matches",
        "wins" to "Victories",
        "losses" to "Defeats",
        "win_rate" to "Win Rate",
        "streak" to "Winning Streak",
        "best_streak" to "Best Streak",
        "rating" to "Elo Rating",
        "total_walls" to "Walls Placed",
        "replay_title" to "Match Replay",
        "move_number" to "Move",
        "step_first" to "Start",
        "step_prev" to "Back",
        "step_play" to "Play",
        "step_pause" to "Pause",
        "step_next" to "Next",
        "step_last" to "End",
        "tutorial_title" to "Interactive Tutorial",
        "tut_step_1_title" to "1. Basic Movement",
        "tut_step_1_desc" to "Tap your pawn and step into any adjacent unblocked square. Your goal is to reach any square in the opponent's starting row!",
        "tut_step_2_title" to "2. Wall Placement",
        "tut_step_2_desc" to "Walls span 2 squares. Place them horizontally or vertically to lengthen your opponent's path.",
        "tut_step_3_title" to "3. Jumping Rivals",
        "tut_step_3_desc" to "When adjacent to an opponent, leap directly over them! If a wall is behind them, you can jump diagonally.",
        "tut_step_4_title" to "4. The Golden Rule: No Trapping",
        "tut_step_4_desc" to "You may never completely seal off a player from their goal. At least one open route must always exist!",
        "tut_step_5_title" to "5. Victory Condition",
        "tut_step_5_desc" to "The first player whose pawn touches any square in the opponent's starting row wins immediately!",

        // Real Network & P2P Keys
        "no_internet_title" to "No Internet Connection",
        "no_internet_msg" to "Online play requires an active internet connection. Please enable Wi-Fi or Mobile Data to play online.",
        "ok" to "OK",
        "p2p_mode_title" to "Play with a Nearby Friend",
        "p2p_mode_desc" to "Connect directly via Hotspot, Wi-Fi, or Bluetooth without needing external servers!",
        "p2p_method_wifi" to "Hotspot / Local Wi-Fi",
        "p2p_method_bt" to "Bluetooth P2P",
        "p2p_host_title" to "Host a Match (Player 1)",
        "p2p_join_title" to "Join Match as Guest (Player 2)",
        "p2p_host_btn" to "Start Hosting Server",
        "p2p_join_btn" to "Connect to Friend",
        "p2p_my_ip" to "Your Local IP Address:",
        "p2p_enter_ip" to "Enter Host IP Address:",
        "p2p_connecting" to "Connecting to friend...",
        "p2p_connected" to "Connected successfully!",
        "p2p_listening" to "Waiting for friend to connect on this network...",
        "p2p_disconnected_title" to "Friend Disconnected",
        "p2p_disconnected_msg" to "Connection with your friend was lost! The match has been terminated.",
        "p2p_bt_paired" to "Paired Bluetooth Devices",
        "p2p_bt_no_devices" to "No paired Bluetooth devices found. Please pair devices in Android settings first.",
        "p2p_bt_host_listening" to "Bluetooth host active. Waiting for connection...",
        "p2p_bt_disabled" to "Bluetooth is currently turned off. Please turn it on in device settings."
    )

    private val ARABIC_MAP = mapOf(
        "app_name" to "WallRush",
        "tagline" to "اقطع طريق الخصم، وافتح طريقك",
        "quick_match" to "مباراة سريعة",
        "quick_match_sub" to "بحث فوري عن خصم حقيقي",
        "play_online" to "اللعب أونلاين",
        "play_online_sub" to "غرف عامة حية ومتجددة",
        "play_friend" to "العب مع صديق",
        "play_friend_sub" to "نقطة اتصال / واي فاي أو بلوتوث",
        "play_ai" to "اللعب ضد الذكاء الاصطناعي",
        "play_ai_sub" to "وضع التدريب التكتيكي",
        "pass_and_play" to "لعب محلي لشخصين",
        "pass_and_play_sub" to "لاعبان على نفس الشاشة",
        "how_to_play" to "كيفية اللعب",
        "how_to_play_sub" to "القواعد والتدريب التفاعلي",
        "leaderboard" to "لوحة الصدارة",
        "profile" to "الملف الشخصي",
        "settings" to "الإعدادات",
        "match_history" to "سجل المباريات",
        "replays" to "إعادة المباريات",
        "searching_opponent" to "جارٍ البحث عن خصم متصل...",
        "cancel" to "إلغاء",
        "ready" to "جاهز",
        "countdown" to "تبدأ المباراة خلال",
        "your_turn" to "دورك الآن",
        "opponents_turn" to "دور الخصم الآن",
        "walls_remaining" to "الجدران المتبقية",
        "place_wall" to "وضع جدار",
        "cancel_wall" to "إلغاء",
        "rotate_wall" to "تدوير (أفقي / رأسي)",
        "confirm_wall" to "تثبيت الجدار",
        "horizontal" to "أفقي",
        "vertical" to "رأسي",
        "resign" to "استسلام",
        "resign_confirm_title" to "هل ترغب في الاستسلام؟",
        "resign_confirm_desc" to "هل أنت متأكد من رغبتك في إعلان الانسحاب وخسارة الجولة؟",
        "rematch" to "إعادة اللعب",
        "menu" to "القائمة الرئيسية",
        "you_win" to "انتصار ساحق!",
        "you_lose" to "هزيمة",
        "draw" to "تعادل",
        "winner_player1" to "فاز اللاعب الأول!",
        "winner_player2" to "فاز اللاعب الثاني!",
        "goal_reached" to "وصل بقطعته إلى خط نهاية الخصم!",
        "time_out" to "فوز بانتهاء وقت الخصم!",
        "resigned_reason" to "استسلم الخصم وأعلن انسحابه!",
        "disconnected_reason" to "انقطع اتصال الخصم! انتهت المباراة.",
        "create_room" to "إنشاء غرفة",
        "join_room" to "انضمام لغرفة",
        "enter_room_code" to "أدخل عنوان IP للمضيف أو الرمز",
        "room_code" to "رمز الغرفة",
        "copy_code" to "نسخ الرمز",
        "share_code" to "مشاركة الرمز",
        "waiting_for_player" to "بانتظار انضمام الخصم...",
        "room_full" to "الغرفة ممتلئة بالكامل",
        "room_not_found" to "تعذر العثور على الغرفة",
        "public_rooms" to "الغرف العامة المباشرة",
        "no_rooms_available" to "لا توجد غرف متاحة حالياً. أنشئ غرفة الآن!",
        "refresh" to "تحديث الغرف",
        "difficulty" to "مستوى الذكاء الاصطناعي",
        "easy" to "مبتدئ (سهل)",
        "medium" to "متوسط",
        "hard" to "محترف (صعب)",
        "time_control" to "نظام الوقت",
        "infinite" to "غير محدود",
        "3_min" to "3 دقائق",
        "5_min" to "5 دقائق",
        "walls_count" to "عدد الجدران لكل لاعب",
        "10_walls" to "10 جدران",
        "15_walls" to "15 جداراً",
        "sound_effects" to "المؤثرات الصوتية",
        "vibration" to "الاهتزاز اللمسي",
        "confirm_wall_toggle" to "طلب تأكيد قبل تثبيت الجدار",
        "show_legal_moves" to "إظهار مؤشرات النقلات المتاحة",
        "language" to "اللغة",
        "game_theme" to "ثيم اللعبة",
        "theme_cyber_neon" to "نيون سايبورغ (الرئيسي)",
        "theme_cyber_neon_desc" to "مظهر نيون متوهج بخطوط شبكية إلكترونية وجدران فسفورية مشعة",
        "theme_deep_slate" to "ديب سليت (الكلاسيكي المحسن)",
        "theme_deep_slate_desc" to "مظهر رمادي داكن هادئ ومريح للعين مع إضاءة زرقاء وحمراء",
        "theme_royal_emerald" to "الزمرد الملكي",
        "theme_royal_emerald_desc" to "مظهر فاخر بدرجات الزمرد الأخضر مع جدران ذهبية براقة",
        "theme_classic_wood" to "الخشب الكلاسيكي",
        "theme_classic_wood_desc" to "مظهر خشبي عريق من خشب الماهوجني الداكن ولمسات نحاسية",
        "theme_obsidian_amber" to "الأوبسيديان والكهرمان",
        "theme_obsidian_amber_desc" to "مظهر صخري داكن فخم بتفاصيل الكهرمان الدافئ والبنفسجي",
        "username" to "اسم اللاعب",
        "save" to "حفظ التغييرات",
        "settings_saved" to "تم حفظ الإعدادات بنجاح",
        "total_games" to "المباريات الملعوبة",
        "wins" to "الانتصارات",
        "losses" to "الهزائم",
        "win_rate" to "نسبة الفوز",
        "streak" to "سلسلة الانتصارات الحالية",
        "best_streak" to "أفضل سلسلة انتصارات",
        "rating" to "نقاط التصنيف (Rating)",
        "total_walls" to "الجدران المشيدة",
        "replay_title" to "إعادة عرض المباراة",
        "move_number" to "النقلة",
        "step_first" to "البداية",
        "step_prev" to "السابقة",
        "step_play" to "تشغيل",
        "step_pause" to "إيقاف مؤقت",
        "step_next" to "التالية",
        "step_last" to "النهاية",
        "tutorial_title" to "التدريب التفاعلي",
        "tut_step_1_title" to "1. الحركة الأساسية",
        "tut_step_1_desc" to "انقر على قطعتك ثم تحرك إلى أي خانة مجاورة غير محجوبة بحاجز. هدفك الأسمى هو الوصول إلى أي خانة في صف بداية الخصم المقابل!",
        "tut_step_2_title" to "2. وضع الجدران العازلة",
        "tut_step_2_desc" to "طول كل جدار خانتان كاملتان. ضعه أفقياً أو رأسياً لإطالة مسار الخصم وإجباره على الالتفاف وتضييع نقلاته.",
        "tut_step_3_title" to "3. القفز فوق المنافس",
        "tut_step_3_desc" to "عندما تتواجه قطعتك مع الخصم وجهاً لوجه، يمكنك القفز مباشرة فوقه! وإذا كان خلفه جدار عازل، يسمح لك بالقفز قطرياً.",
        "tut_step_4_title" to "4. القاعدة الذهبية: حظر الحصار الكامل",
        "tut_step_4_desc" to "يُحظر تماماً وضع جدار يغلق جميع المسارات المؤدية لخط النهاية أمام أي لاعب. يجب أن يظل هناك مسار سالك واحد على الأقل دائماً!",
        "tut_step_5_title" to "5. شروط الفوز",
        "tut_step_5_desc" to "أول لاعب تلمس قطعته أي خانة في خط بداية الخصم يفوز فوراً بالمباراة ويتوج بطلاً!",

        // Real Network & P2P Keys (اللعب ضد صديق بالبلوتوث ونقطة الاتصال والإنترنت)
        "no_internet_title" to "لا يتوفر اتصال بالإنترنت",
        "no_internet_msg" to "يتطلب وضع اللعب عبر الإنترنت اتصالاً نشطاً بالشبكة. يرجى تفعيل Wi-Fi أو بيانات الهاتف للبحث عن لاعبين والانضمام للغرف العامة.",
        "ok" to "حسناً",
        "p2p_mode_title" to "اللعب المباشر مع صديق",
        "p2p_mode_desc" to "اتصال حقيقي مباشر بين جهازين باستخدام نقطة الاتصال (Hotspot)، أو شبكة Wi-Fi محلية، أو البلوتوث الفعلي بدون الحاجة لإنترنت!",
        "p2p_method_wifi" to "نقطة اتصال (Hotspot) / Wi-Fi",
        "p2p_method_bt" to "بلوتوث (Bluetooth P2P)",
        "p2p_host_title" to "إنشاء استضافة (اللاعب 1)",
        "p2p_join_title" to "انضمام إلى الصديق (اللاعب 2)",
        "p2p_host_btn" to "بدء استضافة الغرفة",
        "p2p_join_btn" to "اتصال بجهاز الصديق",
        "p2p_my_ip" to "عنوان IP لجهازك:",
        "p2p_enter_ip" to "أدخل عنوان IP للمضيف:",
        "p2p_connecting" to "جارٍ الاتصال بجهاز الصديق...",
        "p2p_connected" to "تم الاتصال بنجاح! تبدأ المباراة الآن...",
        "p2p_listening" to "في انتظار انضمام الصديق عبر الشبكة...",
        "p2p_disconnected_title" to "انقطع الاتصال بالصديق!",
        "p2p_disconnected_msg" to "تم فقدان الاتصال بين الجهازين! توقفت اللعبة فوراً بسبب إيقاف الاتصال أو انقطاع الشبكة/البلوتوث.",
        "p2p_bt_paired" to "الأجهزة المقترنة بالبلوتوث",
        "p2p_bt_no_devices" to "لا توجد أجهزة بلوتوث مقترنة. يرجى إقران الجهازين أولاً من إعدادات البلوتوث في الهاتف.",
        "p2p_bt_host_listening" to "خادم البلوتوث قيد الانتظار... اطلب من صديقك الاتصال بجهازك الآن.",
        "p2p_bt_disabled" to "البلوتوث غير مفعّل حالياً على جهازك. يرجى تشغيله للمتابعة."
    )
}
